export const SEARCH_INPUT = 'SEARCH_INPUT';
export const SEARCH = 'SEARCH';
export const CANCEL_SEARCH = 'CANCEL_SEARCH';
export const RESULTS_FOUND = 'RESULTS_FOUND';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const UPDATE_CANCEL_TOKEN_SOURCE = 'UPDATE_CANCEL_TOKEN_SOURCE';
